app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from app.db import db
from app.lm import lm
from flask_login import UserMixin


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(16), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    def set_password(self, password):
        self.password_hash = self.get_password_hash(password)

    def get_password_hash(self, password):
        return generate_password_hash(password)

    def verify_password(self, password):
        result = check_password_hash(self.password_hash, password)
        return result

    @staticmethod
    def register(username, password):
        user = User(username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return user

    def __repr__(self):
        return '<User {0}>'.format(self.username)


@lm.user_loader
def load_user(_id):
    return User.query.get(int(_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Submit')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(1, 16)])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
# - *- coding: utf- 8 - *-
import eventlet
eventlet.monkey_patch()
import os
from flask import Flask
from app.sio import socketio
from app.lm import lm
from app.db import db
from app.env import env_assets
from app.bs import bootstrap, bs_init_app
from app.util.assets import bundles
from app.models import User


def create_app(config_name):
    """Create an application instance."""
    app = Flask(__name__)

    # import configuration
    cfg = os.path.join(os.getcwd(), 'config', config_name + '.py')
    app.config.from_pyfile(cfg)

    # initialize extensions
    bootstrap.init_app(app)
    bs_init_app(app)
    db.init_app(app)
    lm.init_app(app)
    socketio.init_app(app, async_mode='eventlet', message_queue='redis://127.0.0.1:6379')

    env_assets.init_app(app)
    env_assets.register(bundles)

    # import blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, redirect, url_for, request, session, copy_current_request_context
from flask_login import login_required, login_user, logout_user
from app.models import User
from app.main.forms import LoginForm, RegistrationForm
from app.sio import socketio
from flask_socketio import emit, join_room, leave_room, close_room, rooms, disconnect
from threading import Lock
from . import main

thread = None
thread_lock = Lock()


def background_thread():
    """Example of how to send server generated events to clients."""
    count = 0
    while True:
        socketio.sleep(10)
        count += 1
        socketio.emit('my_response', {'data': 'Server generated event', 'count': count},  namespace='/test')


@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == 'POST':
        user = User.query.filter_by(username=form.username.data).first()
        verified = user.verify_password(form.password.data)
        if user is None or not verified:
            return redirect(url_for('main.login', **request.args))
        login_user(user)
        return redirect(request.args.get('next') or url_for('main.index'))
    return render_template('login.html', form=form)


@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if request.method == 'POST' and form.validate_on_submit():
        print('Form: ', form)
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            return render_template('registration.html', form=form, message='The user already exists.', type='danger')
        user = User.register(form.username.data, form.password.data)
        message = 'The user "{}" was registered successfully.'.format(user.username)
    else:
        message = None
    return render_template('registration.html', form=form, message=message, type='success')


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/protected')
@login_required
def protected():
    return render_template('protected.html')


@socketio.on('my_event', namespace='/test')
def test_message(message):
    print(message, flush=True)
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response',  {'data': message['data'], 'count': session['receive_count']})


@socketio.on('my_broadcast_event', namespace='/test')
def test_broadcast_message(message):
    print(message, flush=True)
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response', {'data': message['data'], 'count': session['receive_count']}, broadcast=True)


@socketio.on('join', namespace='/test')
def join(message):
    print(message, flush=True)
    join_room(message['room'])
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response', {'data': 'In rooms: ' + ', '.join(rooms()),  'count': session['receive_count']})


@socketio.on('leave', namespace='/test')
def leave(message):
    print(message, flush=True)
    leave_room(message['room'])
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response', {'data': 'In rooms: ' + ', '.join(rooms()), 'count': session['receive_count']})


@socketio.on('close_room', namespace='/test')
def close(message):
    print(message, flush=True)
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response', {'data': 'Room ' + message['room'] + ' is closing.', 'count': session['receive_count']}, room=message['room'])
    close_room(message['room'])


@socketio.on('my_room_event', namespace='/test')
def send_room_message(message):
    print(message, flush=True)
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response', {'data': message['data'], 'count': session['receive_count']}, room=message['room'])


@socketio.on('disconnect_request', namespace='/test')
def disconnect_request():
    print({'data': "Disconnecting.", 'count': session['receive_count']}, flush=True)
    @copy_current_request_context
    def can_disconnect():
        disconnect()

    session['receive_count'] = session.get('receive_count', 0) + 1
    # for this emit we use a callback function
    # when the callback function is invoked we know that the message has been
    # received and it is safe to disconnect
    emit('my_response', {'data': 'Disconnected!', 'count': session['receive_count']}, callback=can_disconnect)


@socketio.on('my_ping', namespace='/test')
def ping_pong():
    print({'data': "Haha My Pong.", 'count': session['receive_count']}, flush=True)
    emit('my_pong')


@socketio.on('connect', namespace='/test')
def test_connect():
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(background_thread)
    emit('my_response', {'data': 'Connected', 'count': 0})


@socketio.on('disconnect', namespace='/test')
def test_disconnect():
    print('Client disconnected', request.sid)

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Login Example{% endblock %}

{%- block styles %}
    <!-- Bootstrap -->
    <link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
    <link href="{{bootstrap_find_resource('css/all.css', cdn='fontawesome')}}" rel="stylesheet">
{%- endblock styles %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">
            Login Example
        </a>
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{{ url_for('main.index') }}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('main.protected') }}">Protected</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
                {% endif %}
            </li>
            <li class="nav-item">
                {% if current_user.is_authenticated == false %}
                    <a  class="nav-link"href="{{ url_for('main.register') }}">Register</a>
                {% endif %}
            </li>
        </ul>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Login Example{% endblock %}

{% block page_content %}
    <h1>Home page</h1>
    <p>This page can be viewed by all users.</p>
    <p>You are {% if not current_user.is_authenticated %}not {% endif %}logged in.</p>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Login Example{% endblock %}

{% block page_content %}
    <h1>Login</h1>
    <div class="row">
        <div class="col-md-3">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/protected.html
{% extends "base.html" %}

{% block scripts %}
    {{super()}}
    {% assets "protected_js" %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/socket.js') }}"></script>
{% endblock %}

{% block title %}Login Example{% endblock %}

{% block page_content %}
    <h1>Flask-SocketIO Test</h1>
    <p>Async mode is: <b>{{ async_mode }}</b></p>
    <p>Average ping/pong latency: <b><span id="ping-pong"></span>ms</b></p>
    <h2>Send:</h2>
    <form id="emit" method="POST" action='#'>
        <input type="text" name="emit_data" id="emit_data" placeholder="Message">
        <input type="submit" value="Echo">
    </form>
    <form id="broadcast" method="POST" action='#'>
        <input type="text" name="broadcast_data" id="broadcast_data" placeholder="Message">
        <input type="submit" value="Broadcast">
    </form>
    <form id="join" method="POST" action='#'>
        <input type="text" name="join_room" id="join_room" placeholder="Room Name">
        <input type="submit" value="Join Room">
    </form>
    <form id="leave" method="POST" action='#'>
        <input type="text" name="leave_room" id="leave_room" placeholder="Room Name">
        <input type="submit" value="Leave Room">
    </form>
    <form id="send_room" method="POST" action='#'>
        <input type="text" name="room_name" id="room_name" placeholder="Room Name">
        <input type="text" name="room_data" id="room_data" placeholder="Message">
        <input type="submit" value="Send to Room">
    </form>
    <form id="close" method="POST" action="#">
        <input type="text" name="close_room" id="close_room" placeholder="Room Name">
        <input type="submit" value="Close Room">
    </form>
    <form id="disconnect" method="POST" action="#">
        <input type="submit" value="Disconnect">
    </form>
    <h2>Receive:</h2>
    <div id="log"></div>
    <p>This page can only be viewed by logged in users.</p>
    <p>You are logged in as <b>{{ current_user.username }}</b>.</p>
{% endblock %}

app/templates/registration.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Registration Example{% endblock %}

{% block page_content %}
    <h1>Registration</h1>
    {% if message != None %}
        <div class="alert alert-{{type}} alert-dismissible" role="alert">
          {{ message }}
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-3">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}